toolbar:
  - cut copy paste | undo redo | searchreplace | fullscreen | cap1 cap2 cap3 cap4
  - bold italic underline strikethrough superscript subscript | numlist bullist | image link | latex | code
  
plugins:
  - image
  - link
  - botoes
  - lists
  - fullscreen
  - searchreplace
  - wordcount
  - paste
  - code
 


