toolbar:
  - cut copy paste | undo redo | searchreplace | fullscreen |  formatselectbr 
  - bold italic underline strikethrough superscript subscript | numlist bullist | imagem link | latex | code
  
plugins:
  - image
  - link
  - botoes
  - lists
  - fullscreen
  - searchreplace
  - wordcount
  - paste
  - code
 


